In [66]:
# Initial imports.
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn import tree

In [67]:
#load in the csv file for model
df = pd.read_csv('resources/GTA_houses_cleaned.csv')
df.head()

,Unnamed: 0,listing image,listing url,full address,city,zipcode,# of beds,# of bathrooms,price,latitude,longitude,home type
0,0,https://photos.zillowstatic.com/fp/23aacb3df57...,https://www.zillow.com/homedetails/6225-Lawren...,"6225 Lawrence Ave E, Toronto, ON M1C 5G4",Toronto,M1C5G4,3,4,799900,43.655720,-79.457450,SINGLE_FAMILY
1,2,https://photos.zillowstatic.com/fp/1cd388cbfce...,https://www.zillow.com/homedetails/3840-Bathur...,"3840 Bathurst St #702, Toronto, ON M3H 6C6",Toronto,M3H6C6,2,2,699000,43.623860,-79.488945,CONDO
2,3,https://photos.zillowstatic.com/fp/1f0037527b3...,https://www.zillow.com/homedetails/8-Littlelea...,"8 Littleleaf Dr, Toronto, ON M1B 1Z1",Toronto,M1B1Z1,3,3,1149900,43.723150,-79.448230,CONDO
3,4,https://photos.zillowstatic.com/fp/780ba993641...,https://www.zillow.com/homedetails/2301-Danfor...,"2301 Danforth Ave #306, Toronto, ON M4C 0A7",Toronto,M4C0A7,2,2,699000,43.642390,-79.424736,CONDO
4,5,https://photos.zillowstatic.com/fp/950875d10ea...,https://www.zillow.com/homedetails/16-Catalda-...,"16 Catalda Ct, Toronto, ON M2R 3X5",Toronto,M2R3X5,4,5,2690000,43.641495,-79.410070,CONDO

In [68]:
#check how many rows and columns we have
df.shape

(1908, 12)

In [69]:
df = pd.get_dummies(df, columns=["home type", "# of beds"])
df.head()

,Unnamed: 0,listing image,listing url,full address,city,zipcode,# of bathrooms,price,latitude,longitude,home type_CONDO,home type_SINGLE_FAMILY,home type_TOWNHOUSE,# of beds_1,# of beds_2,# of beds_3,# of beds_4,# of beds_5
0,0,https://photos.zillowstatic.com/fp/23aacb3df57...,https://www.zillow.com/homedetails/6225-Lawren...,"6225 Lawrence Ave E, Toronto, ON M1C 5G4",Toronto,M1C5G4,4,799900,43.655720,-79.457450,0,1,0,0,0,1,0,0
1,2,https://photos.zillowstatic.com/fp/1cd388cbfce...,https://www.zillow.com/homedetails/3840-Bathur...,"3840 Bathurst St #702, Toronto, ON M3H 6C6",Toronto,M3H6C6,2,699000,43.623860,-79.488945,1,0,0,0,1,0,0,0
2,3,https://photos.zillowstatic.com/fp/1f0037527b3...,https://www.zillow.com/homedetails/8-Littlelea...,"8 Littleleaf Dr, Toronto, ON M1B 1Z1",Toronto,M1B1Z1,3,1149900,43.723150,-79.448230,1,0,0,0,0,1,0,0
3,4,https://photos.zillowstatic.com/fp/780ba993641...,https://www.zillow.com/homedetails/2301-Danfor...,"2301 Danforth Ave #306, Toronto, ON M4C 0A7",Toronto,M4C0A7,2,699000,43.642390,-79.424736,1,0,0,0,1,0,0,0
4,5,https://photos.zillowstatic.com/fp/950875d10ea...,https://www.zillow.com/homedetails/16-Catalda-...,"16 Catalda Ct, Toronto, ON M2R 3X5",Toronto,M2R3X5,5,2690000,43.641495,-79.410070,1,0,0,0,0,0,1,0

In [ ]:
#delete first column as it is unneeded
df = df.iloc[: , 1:]
df.head()

In [72]:
# Define the features set.
X = df.copy()
X = X.drop(['price', 'listing image', 'listing url', 'full address', 'zipcode', 'latitude', 'longitude', 'city', '# of bathrooms', 'Unnamed: 0'], axis=1)
X.head()

,home type_CONDO,home type_SINGLE_FAMILY,home type_TOWNHOUSE,# of beds_1,# of beds_2,# of beds_3,# of beds_4,# of beds_5
0,0,1,0,0,0,1,0,0
1,1,0,0,0,1,0,0,0
2,1,0,0,0,0,1,0,0
3,1,0,0,0,1,0,0,0
4,1,0,0,0,0,0,1,0

In [73]:
X.shape

(1908, 8)

In [74]:
# Define the target set.
y = df['price']
y[:15]

0      799900
1      699000
2     1149900
3      699000
4     2690000
5      829000
6      299999
7      924900
8      769000
9     7288000
10     649900
11    1185000
12     799000
13     999000
14     750000
Name: price, dtype: int64

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2, train_size=0.75)

In [76]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1431, 8)
(477, 8)
(1431,)
(477,)

In [77]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [78]:
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train_scaled, y_train)

In [79]:
# Making predictions using the testing data.
predictions = model.predict(X_test_scaled)
print(predictions)

[ 699000 1199000 1199000  699900  599000  599000 1399000  699000  699000
 1399000  999000  749000  699000 1199000 1199000 1199000  699900 1199000
 1199000  699900  699000  699000 1199000  699000 1399000  699000  499000
  999000  699000 1199000 1199000 1199000  649900  699000  999000  699900
  999000  699900 1399000  699900  699000  499000  499000 1199000 1399000
  999000  699000  699000 1399000  699000 1199000 1399000  599000  999000
 1399000 1399000 1399000  699900  999000 1199000  499000 1199000 1399000
 1199000  699000  499000  699000 1199000  699000  999000 1399000 1399000
  499000 1199000 1199000  699000  499000  499000  699000  499000  999000
  699000  999000 1199000 1199000 1199000  499000 1399000  499000 1399000
 1199000 1399000 1399000 1399000 1399000 1199000  699000 1199000  499000
  699900 1399000  699000  999000  699000  999000  749000 1199000  649900
  699000  699000 1399000 1199000 1399000 1199000  699000 1399000 1399000
  699900 1199000 1199000 1399000  999000  749000  749000 1399000  499000
 1199000  699900  649900  699900  649900  499000  699000 1399000  579900
 1399000 1199000 1199000  469900 1399000 1199000  499000 1399000  699000
  649900 1399000 1399000 1399000 1199000  579900  499000  699900  649900
 1399000  699000 1199000  699000  699900  699000  499000 1199000 1399000
 1399000 1199000 1199000 1399000  699000  699000  999000 1199000 1399000
 1199000  999000  999000  699000 1399000 1199000  579900 1199000 1199000
  699000 1399000 1399000  699000 1199000  699900 1399000 1199000 1399000
 1399000 1399000 1399000 1199000 1199000  999000  999000  699000  699000
 1399000 1399000 1399000  649900 1199000 1199000  699000  699000 1199000
  699000  599000  649900  699900  699900 1399000  649900  699000 1199000
  699000 1199000 1399000  469900  699000 1399000 1399000  699000  999000
 1199000  699000  699000 1399000  499000  699000  999000 1199000  699000
 1199000 1199000 1199000  699000 1399000 1399000  999000  999000 1199000
 1399000 1199000  649900  999000  699000  499000  999000 1199000 1199000
  699900 1199000  999000 1199000 1199000 1399000  999000  499000 1399000
 1199000  499000 1399000  499000 1399000  999000  599000 1199000 1199000
 1399000 1199000  999000  699000  749000  999000  499000  699000  999000
 1399000 1399000  699000  699900 1199000 1199000 1199000 1399000  999000
  499000 1199000 1399000 1399000 1199000 1399000  469900 1399000  999000
  999000 1199000  699000  499000  699000  999000 1399000 1399000 1399000
 1199000 1199000  699000 1399000 1199000 1199000 1399000  649900  699000
 1399000  499000  699000 1199000  999000  699000  699000 1199000  699000
 1199000  699900  749000  649900  499000  699000 1399000  999000 1399000
 1199000  699000  699000 1399000 1399000  699900 1399000 1399000  699000
  699900 1199000 1199000 1199000 1399000 1399000  699000  999000 1199000
  699000  699000  699000 1399000  999000  499000  699000 1199000  499000
 1399000 1399000  699000  699000 1399000 1399000 1199000  499000  699900
 1199000 1399000  599000 1199000  999000 1399000  699900  999000 1399000
 1199000 1199000 1199000  499000  699000  579900  649900  749000 1399000
 1199000  499000 1399000  749000 1199000  999000 1199000  999000  999000
  999000 1399000 1399000  999000  579900  699000  699000 1399000 1199000
  699000 1199000  699000  649900  499000  599000 1399000 1399000  499000
 1199000 1199000 1199000 1399000 1399000  999000  999000 1399000  499000
 1199000 1199000  599000 1399000 1399000 1399000  649900 1399000  999000
  499000 1399000  699000  999000  999000 1399000  599000 1199000  999000
  599000 1199000 1399000  579900 1399000 1399000  699900 1399000  699000
 1199000 1199000  999000 1399000 1399000 1199000 1199000 1399000  649900
  999000 1399000 1399000 1399000 1199000 1199000 1199000  699900  999000
  499000  699000  579900  999000 1199000  999000  999000  999000 1199000]

In [80]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
print(acc_score)
print(classification_report(y_test, predictions))

0.020964360587002098
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         2
        2900       0.00      0.00      0.00         1
       45000       0.00      0.00      0.00         1
       88888       0.00      0.00      0.00         1
      199900       0.00      0.00      0.00         1
      225000       0.00      0.00      0.00         1
      229000       0.00      0.00      0.00         1
      298000       0.00      0.00      0.00         1
      317000       0.00      0.00      0.00         1
      320000       0.00      0.00      0.00         1
      330000       0.00      0.00      0.00         1
      339900       0.00      0.00      0.00         1
      349000       0.00      0.00      0.00         1
      415000       0.00      0.00      0.00         1
      449900       0.00      0.00      0.00         1
      469900       0.00      0.00      0.00         0
      475000       0.00      0.00      0.00         1
      479000       0.00      0.00      0.00         1
      479900       0.00      0.00      0.00         1
      489900       0.00      0.00      0.00         1
      498888       0.00      0.00      0.00         1
      499000       0.00      0.00      0.00         0
      499900       0.00      0.00      0.00         2
      535000       0.00      0.00      0.00         1
      549900       0.00      0.00      0.00         2
      559000       0.00      0.00      0.00         1
      569900       0.00      0.00      0.00         2
      579900       0.00      0.00      0.00         0
      588000       0.00      0.00      0.00         2
      594900       0.00      0.00      0.00         1
      599000       0.00      0.00      0.00         3
      599888       0.00      0.00      0.00         1
      599900       0.00      0.00      0.00         5
      599999       0.00      0.00      0.00         1
      609900       0.00      0.00      0.00         2
      614990       0.00      0.00      0.00         1
      619900       0.00      0.00      0.00         1
      638000       0.00      0.00      0.00         1
      649000       0.00      0.00      0.00         4
      649900       0.06      0.25      0.10         4
      649999       0.00      0.00      0.00         1
      669000       0.00      0.00      0.00         1
      669900       0.00      0.00      0.00         1
      675000       0.00      0.00      0.00         2
      685000       0.00      0.00      0.00         1
      695000       0.00      0.00      0.00         1
      699000       0.05      0.50      0.09         8
      699900       0.00      0.00      0.00         1
      699990       0.00      0.00      0.00         1
      715000       0.00      0.00      0.00         1
      718000       0.00      0.00      0.00         1
      719000       0.00      0.00      0.00         1
      719800       0.00      0.00      0.00         1
      729000       0.00      0.00      0.00         3
      740000       0.00      0.00      0.00         1
      749000       0.00      0.00      0.00         2
      750000       0.00      0.00      0.00         2
      764900       0.00      0.00      0.00         1
      765000       0.00      0.00      0.00         1
      777777       0.00      0.00      0.00         1
      779000       0.00      0.00      0.00         1
      785000       0.00      0.00      0.00         1
      789000       0.00      0.00      0.00         1
      790000       0.00      0.00      0.00         1
      799000       0.00      0.00      0.00         7
      799900       0.00      0.00      0.00         9
      824900       0.00      0.00      0.00         1
      828000       0.00      0.00      0.00         1
      838000       0.00      0.00      0.00         1
      839900       0.00      0.00      0.00         1
      849500       0.00      0.00      0.00         1
      849900       0.00      0.00      0.00         1
      859000       0.00      0.00      0.00         1
      865000       0.00      0.00      0.00         1
      869000       0.00      0.00      0.00         1
      874900       0.00      0.00      0.00         1
      875000       0.00      0.00      0.00         2
      879000       0.00      0.00      0.00         1
      879900       0.00      0.00      0.00         1
      888000       0.00      0.00      0.00         1
      898000       0.00      0.00      0.00         1
      899000       0.00      0.00      0.00         8
      899900       0.00      0.00      0.00         2
      899999       0.00      0.00      0.00         3
      924900       0.00      0.00      0.00         1
      928000       0.00      0.00      0.00         1
      929000       0.00      0.00      0.00         1
      939900       0.00      0.00      0.00         2
      947500       0.00      0.00      0.00         1
      948800       0.00      0.00      0.00         1
      949000       0.00      0.00      0.00         2
      949888       0.00      0.00      0.00         1
      949900       0.00      0.00      0.00         2
      949999       0.00      0.00      0.00         1
      959000       0.00      0.00      0.00         1
      969000       0.00      0.00      0.00         2
      975000       0.00      0.00      0.00         1
      979999       0.00      0.00      0.00         1
      980000       0.00      0.00      0.00         2
      989000       0.00      0.00      0.00         1
      992000       0.00      0.00      0.00         2
      995000       0.00      0.00      0.00         1
      998000       0.00      0.00      0.00         4
      998800       0.00      0.00      0.00         1
      999000       0.00      0.00      0.00        12
      999800       0.00      0.00      0.00         1
      999888       0.00      0.00      0.00         1
      999900       0.00      0.00      0.00         5
      999990       0.00      0.00      0.00         1
      999999       0.00      0.00      0.00         2
     1025900       0.00      0.00      0.00         1
     1038000       0.00      0.00      0.00         1
     1049900       0.00      0.00      0.00         1
     1059000       0.00      0.00      0.00         1
     1080000       0.00      0.00      0.00         1
     1088000       0.00      0.00      0.00         2
     1099000       0.00      0.00      0.00         9
     1099900       0.00      0.00      0.00         2
     1099998       0.00      0.00      0.00         1
     1099999       0.00      0.00      0.00         1
     1100000       0.00      0.00      0.00         1
     1130000       0.00      0.00      0.00         1
     1135000       0.00      0.00      0.00         1
     1139900       0.00      0.00      0.00         1
     1148000       0.00      0.00      0.00         1
     1149000       0.00      0.00      0.00         2
     1149888       0.00      0.00      0.00         1
     1149900       0.00      0.00      0.00         1
     1150000       0.00      0.00      0.00         4
     1156000       0.00      0.00      0.00         1
     1159999       0.00      0.00      0.00         1
     1164888       0.00      0.00      0.00         1
     1169900       0.00      0.00      0.00         1
     1174000       0.00      0.00      0.00         1
     1175000       0.00      0.00      0.00         2
     1189000       0.00      0.00      0.00         2
     1189900       0.00      0.00      0.00         1
     1190000       0.00      0.00      0.00         1
     1195000       0.00      0.00      0.00         1
     1198000       0.00      0.00      0.00         1
     1198888       0.00      0.00      0.00         1
     1199000       0.02      0.40      0.03         5
     1200000       0.00      0.00      0.00         1
     1225000       0.00      0.00      0.00         1
     1229000       0.00      0.00      0.00         2
     1248000       0.00      0.00      0.00         1
     1248888       0.00      0.00      0.00         1
     1249000       0.00      0.00      0.00         3
     1249900       0.00      0.00      0.00         2
     1250000       0.00      0.00      0.00         2
     1280000       0.00      0.00      0.00         2
     1285000       0.00      0.00      0.00         1
     1288000       0.00      0.00      0.00         1
     1288900       0.00      0.00      0.00         1
     1289000       0.00      0.00      0.00         1
     1290000       0.00      0.00      0.00         1
     1298000       0.00      0.00      0.00         1
     1298800       0.00      0.00      0.00         1
     1299000       0.00      0.00      0.00         5
     1299800       0.00      0.00      0.00         2
     1299900       0.00      0.00      0.00         2
     1299988       0.00      0.00      0.00         1
     1299999       0.00      0.00      0.00         1
     1300000       0.00      0.00      0.00         3
     1328000       0.00      0.00      0.00         1
     1349000       0.00      0.00      0.00         2
     1349900       0.00      0.00      0.00         1
     1375000       0.00      0.00      0.00         2
     1379000       0.00      0.00      0.00         1
     1388000       0.00      0.00      0.00         1
     1395000       0.00      0.00      0.00         1
     1399000       0.03      0.75      0.05         4
     1399800       0.00      0.00      0.00         1
     1399900       0.00      0.00      0.00         1
     1410000       0.00      0.00      0.00         1
     1415000       0.00      0.00      0.00         1
     1438888       0.00      0.00      0.00         1
     1449000       0.00      0.00      0.00         1
     1449900       0.00      0.00      0.00         1
     1450000       0.00      0.00      0.00         3
     1469000       0.00      0.00      0.00         2
     1474900       0.00      0.00      0.00         1
     1488000       0.00      0.00      0.00         1
     1489000       0.00      0.00      0.00         1
     1495000       0.00      0.00      0.00         1
     1499000       0.00      0.00      0.00         5
     1499800       0.00      0.00      0.00         1
     1499900       0.00      0.00      0.00         2
     1500000       0.00      0.00      0.00         1
     1548000       0.00      0.00      0.00         1
     1549999       0.00      0.00      0.00         1
     1558000       0.00      0.00      0.00         1
     1570000       0.00      0.00      0.00         1
     1575000       0.00      0.00      0.00         1
     1588000       0.00      0.00      0.00         2
     1588800       0.00      0.00      0.00         1
     1589000       0.00      0.00      0.00         1
     1590000       0.00      0.00      0.00         1
     1595000       0.00      0.00      0.00         1
     1598888       0.00      0.00      0.00         1
     1599000       0.00      0.00      0.00         6
     1608000       0.00      0.00      0.00         1
     1628000       0.00      0.00      0.00         1
     1630000       0.00      0.00      0.00         1
     1650000       0.00      0.00      0.00         1
     1669000       0.00      0.00      0.00         1
     1685000       0.00      0.00      0.00         1
     1699000       0.00      0.00      0.00         4
     1699999       0.00      0.00      0.00         1
     1700000       0.00      0.00      0.00         1
     1729000       0.00      0.00      0.00         1
     1739000       0.00      0.00      0.00         1
     1749000       0.00      0.00      0.00         2
     1750000       0.00      0.00      0.00         1
     1750088       0.00      0.00      0.00         1
     1758888       0.00      0.00      0.00         1
     1785000       0.00      0.00      0.00         1
     1788000       0.00      0.00      0.00         1
     1789000       0.00      0.00      0.00         1
     1790000       0.00      0.00      0.00         1
     1798000       0.00      0.00      0.00         2
     1798800       0.00      0.00      0.00         1
     1798888       0.00      0.00      0.00         1
     1799000       0.00      0.00      0.00         4
     1799800       0.00      0.00      0.00         1
     1799990       0.00      0.00      0.00         1
     1819000       0.00      0.00      0.00         1
     1825000       0.00      0.00      0.00         1
     1829900       0.00      0.00      0.00         1
     1848000       0.00      0.00      0.00         1
     1849000       0.00      0.00      0.00         1
     1895000       0.00      0.00      0.00         1
     1899000       0.00      0.00      0.00         1
     1899888       0.00      0.00      0.00         2
     1899900       0.00      0.00      0.00         2
     1918800       0.00      0.00      0.00         1
     1948000       0.00      0.00      0.00         1
     1975000       0.00      0.00      0.00         1
     1999000       0.00      0.00      0.00         1
     1999900       0.00      0.00      0.00         3
     2000000       0.00      0.00      0.00         1
     2099000       0.00      0.00      0.00         1
     2100000       0.00      0.00      0.00         4
     2189000       0.00      0.00      0.00         1
     2199000       0.00      0.00      0.00         3
     2199999       0.00      0.00      0.00         1
     2200000       0.00      0.00      0.00         1
     2220000       0.00      0.00      0.00         1
     2225000       0.00      0.00      0.00         1
     2249000       0.00      0.00      0.00         1
     2249777       0.00      0.00      0.00         1
     2299888       0.00      0.00      0.00         1
     2299900       0.00      0.00      0.00         1
     2318000       0.00      0.00      0.00         1
     2349000       0.00      0.00      0.00         1
     2350000       0.00      0.00      0.00         1
     2375000       0.00      0.00      0.00         1
     2388000       0.00      0.00      0.00         1
     2390000       0.00      0.00      0.00         1
     2395000       0.00      0.00      0.00         1
     2398000       0.00      0.00      0.00         1
     2399000       0.00      0.00      0.00         1
     2399999       0.00      0.00      0.00         1
     2458000       0.00      0.00      0.00         1
     2480000       0.00      0.00      0.00         1
     2488000       0.00      0.00      0.00         1
     2490000       0.00      0.00      0.00         1
     2495000       0.00      0.00      0.00         1
     2499000       0.00      0.00      0.00         3
     2525000       0.00      0.00      0.00         1
     2659000       0.00      0.00      0.00         1
     2690000       0.00      0.00      0.00         1
     2698000       0.00      0.00      0.00         1
     2800000       0.00      0.00      0.00         1
     2890000       0.00      0.00      0.00         1
     2895000       0.00      0.00      0.00         1
     2899000       0.00      0.00      0.00         1
     2950000       0.00      0.00      0.00         1
     2999000       0.00      0.00      0.00         1
     2999850       0.00      0.00      0.00         2
     2999900       0.00      0.00      0.00         1
     3100000       0.00      0.00      0.00         1
     3110000       0.00      0.00      0.00         1
     3149000       0.00      0.00      0.00         1
     3169000       0.00      0.00      0.00         1
     3198000       0.00      0.00      0.00         1
     3250000       0.00      0.00      0.00         1
     3288000       0.00      0.00      0.00         1
     3300000       0.00      0.00      0.00         1
     3350000       0.00      0.00      0.00         1
     3398000       0.00      0.00      0.00         1
     3490000       0.00      0.00      0.00         1
     3650000       0.00      0.00      0.00         1
     3688000       0.00      0.00      0.00         1
     3698000       0.00      0.00      0.00         1
     3777000       0.00      0.00      0.00         1
     3790000       0.00      0.00      0.00         1
     3899000       0.00      0.00      0.00         1
     3995000       0.00      0.00      0.00         1
     4175000       0.00      0.00      0.00         1
     4350000       0.00      0.00      0.00         1
     4388800       0.00      0.00      0.00         1
     4488000       0.00      0.00      0.00         2
     4488800       0.00      0.00      0.00         1
     4498000       0.00      0.00      0.00         1
     4500000       0.00      0.00      0.00         1
     4600000       0.00      0.00      0.00         1
     4688000       0.00      0.00      0.00         1
     4995000       0.00      0.00      0.00         1
     4998000       0.00      0.00      0.00         1
     5095000       0.00      0.00      0.00         1
     5495000       0.00      0.00      0.00         1
     5999900       0.00      0.00      0.00         1
     6000000       0.00      0.00      0.00         1
     6490000       0.00      0.00      0.00         1
     6498000       0.00      0.00      0.00         1
     6600000       0.00      0.00      0.00         1
     6888000       0.00      0.00      0.00         1
     7188000       0.00      0.00      0.00         1
     7395000       0.00      0.00      0.00         1
     8000000       0.00      0.00      0.00         1
     8100000       0.00      0.00      0.00         1
     8995000       0.00      0.00      0.00         1
    10500000       0.00      0.00      0.00         1
    11000000       0.00      0.00      0.00         1
    12998888       0.00      0.00      0.00         1

    accuracy                           0.02       477
   macro avg       0.00      0.01      0.00       477
weighted avg       0.00      0.02      0.00       477

C:\Users\Ari\anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ari\anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ari\anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ari\anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ari\anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Ari\anaconda3\envs\mlenv\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()
scaled = data_scaler.fit_transform(df)
scaled[:5]

In [ ]:
import numpy as np
print(np.mean(scaled[:,0]))
print(np.std(scaled[:,0]))