In [7]:
# import liberaries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
%matplotlib inline

# import data

houses = pd.read_csv('resources/GTA_houses_cleaned.csv')
df = houses
df.head(10)

,listing image,listing url,full address,city,zipcode,# of beds,# of bathrooms,price,latitude,longitude,home type
0,https://photos.zillowstatic.com/fp/23aacb3df57...,https://www.zillow.com/homedetails/6225-Lawren...,"6225 Lawrence Ave E, Toronto, ON M1C 5G4",Toronto,M1C5G4,3,4,799900,43.655720,-79.457450,SINGLE_FAMILY
1,https://photos.zillowstatic.com/fp/1cd388cbfce...,https://www.zillow.com/homedetails/3840-Bathur...,"3840 Bathurst St #702, Toronto, ON M3H 6C6",Toronto,M3H6C6,2,2,699000,43.623860,-79.488945,CONDO
2,https://photos.zillowstatic.com/fp/1f0037527b3...,https://www.zillow.com/homedetails/8-Littlelea...,"8 Littleleaf Dr, Toronto, ON M1B 1Z1",Toronto,M1B1Z1,3,3,1149900,43.723150,-79.448230,CONDO
3,https://photos.zillowstatic.com/fp/780ba993641...,https://www.zillow.com/homedetails/2301-Danfor...,"2301 Danforth Ave #306, Toronto, ON M4C 0A7",Toronto,M4C0A7,2,2,699000,43.642390,-79.424736,CONDO
4,https://photos.zillowstatic.com/fp/950875d10ea...,https://www.zillow.com/homedetails/16-Catalda-...,"16 Catalda Ct, Toronto, ON M2R 3X5",Toronto,M2R3X5,4,5,2690000,43.641495,-79.410070,CONDO
5,https://photos.zillowstatic.com/fp/e9d5059a0e5...,https://www.zillow.com/homedetails/2460-Eglint...,"2460 Eglinton Ave E PENTHOUSE 12, Toronto, ON ...",Toronto,M1K5J7,2,2,829000,43.718020,-79.376884,CONDO
6,https://photos.zillowstatic.com/fp/738f0093a9e...,https://www.zillow.com/homedetails/7-Brimley-R...,"7 Brimley Rd S #E31, Toronto, ON M1M 3W3",Toronto,M1M3W3,1,1,299999,43.714500,-79.453510,CONDO
7,https://photos.zillowstatic.com/fp/f886851510b...,https://www.zillow.com/homedetails/17-Caddy-Dr...,"17 Caddy Dr, Toronto, ON M1G 2E9",Toronto,M1G2E9,3,2,924900,43.641552,-79.424515,CONDO
8,https://photos.zillowstatic.com/fp/2526282e0ca...,https://www.zillow.com/homedetails/441-Jane-St...,"441 Jane St #109, Toronto, ON M6S 3Z9",Toronto,M6S3Z9,2,2,769000,43.589770,-79.545170,CONDO
9,https://photos.zillowstatic.com/fp/79fe2faa6e0...,https://www.zillow.com/homedetails/121-Forest-...,"121 Forest Heights Blvd, Toronto, ON M2L 2K7",Toronto,M2L2K7,4,6,7288000,43.780040,-79.412680,CONDO

In [9]:
from sklearn.preprocessing import LabelEncoder



# dropping Unnamed column, axis = 1 means we are dropping column


# Creating categorical variables


#categorical_features = ['city', 'home type']
#le = LabelEncoder()


# Converting the variables to some sort of numerical
#for i in range(2):

    #new = le.fit_transform(df[categorical_features[i]])
    
    #df[categorical_features[i]] = new
    
#df.head(5)

df = pd.get_dummies(df, columns=['city', 'home type'])
df.head()

,listing image,listing url,full address,zipcode,# of beds,# of bathrooms,price,latitude,longitude,city_Brampton,city_Markham,city_Mississauga,city_Toronto,city_Vaughan,home type_CONDO,home type_SINGLE_FAMILY,home type_TOWNHOUSE
0,https://photos.zillowstatic.com/fp/23aacb3df57...,https://www.zillow.com/homedetails/6225-Lawren...,"6225 Lawrence Ave E, Toronto, ON M1C 5G4",M1C5G4,3,4,799900,43.655720,-79.457450,0,0,0,1,0,0,1,0
1,https://photos.zillowstatic.com/fp/1cd388cbfce...,https://www.zillow.com/homedetails/3840-Bathur...,"3840 Bathurst St #702, Toronto, ON M3H 6C6",M3H6C6,2,2,699000,43.623860,-79.488945,0,0,0,1,0,1,0,0
2,https://photos.zillowstatic.com/fp/1f0037527b3...,https://www.zillow.com/homedetails/8-Littlelea...,"8 Littleleaf Dr, Toronto, ON M1B 1Z1",M1B1Z1,3,3,1149900,43.723150,-79.448230,0,0,0,1,0,1,0,0
3,https://photos.zillowstatic.com/fp/780ba993641...,https://www.zillow.com/homedetails/2301-Danfor...,"2301 Danforth Ave #306, Toronto, ON M4C 0A7",M4C0A7,2,2,699000,43.642390,-79.424736,0,0,0,1,0,1,0,0
4,https://photos.zillowstatic.com/fp/950875d10ea...,https://www.zillow.com/homedetails/16-Catalda-...,"16 Catalda Ct, Toronto, ON M2R 3X5",M2R3X5,4,5,2690000,43.641495,-79.410070,0,0,0,1,0,1,0,0

In [10]:
df.to_csv('GTA_houses_cleaned.csv', index=False)

In [14]:
X = df.drop(['price', 'listing image', 'listing url', 'full address', 'zipcode', 'latitude', 'longitude'], axis=1)

y = df[['price']]

In [15]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split


# Splitting data into training and test sets


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 25, random_state = 101)


# Train the Model


regr = RandomForestRegressor(n_estimators = 10, max_depth = 10, random_state = 101)
regr.fit(X_train, y_train.values.ravel())

RandomForestRegressor(max_depth=10, n_estimators=10, random_state=101)

In [16]:
import warnings
warnings.filterwarnings('ignore')


# Make prediction
predictions = regr.predict(X_test)


result = X_test
result['price'] = y_test
result['prediction'] = predictions.tolist()


result.head()

,# of beds,# of bathrooms,city_Brampton,city_Markham,city_Mississauga,city_Toronto,city_Vaughan,home type_CONDO,home type_SINGLE_FAMILY,home type_TOWNHOUSE,price,prediction
1053,3,3,0,1,0,0,0,1,0,0,1069900,8.064366e+05
1783,4,5,0,0,0,0,1,0,1,0,1650000,2.614777e+06
822,4,4,1,0,0,0,0,0,1,0,1299000,1.405302e+06
882,4,4,1,0,0,0,0,0,1,0,1669000,1.405302e+06
524,4,3,0,0,0,1,0,0,1,0,875000,1.475312e+06

In [9]:
# Define x axis
x_axis = X_test.


# Build scatterplot

plt.scatter(x_axis, y_test, c = 'b', alpha = 0.5, marker = '.', label = 'Real')
plt.scatter(x_axis, predictions, c = 'r', alpha = 0.5, marker = '.', label = 'Predicted')

plt.xlabel('city')
plt.ylabel('price')

plt.grid(color = '#D3D3D3', linestyle = 'solid')

plt.legend(loc = 'lower right')

plt.show()

AttributeError: 'DataFrame' object has no attribute 'city'

In [17]:
# importing necessary liberaries


from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error


# Mean squared error (MSE)
mse = mean_squared_error(y_test.values.ravel(), predictions)


# R2 Score
r2 = r2_score(y_test.values.ravel(), predictions)


# Mean Absolute Error
mae = mean_absolute_error(y_test.values.ravel(), predictions)


#Print Results


print("Mean squared error (MSE): ", round(mse, 2))

print("R2 Score: ", round(r2, 2))
print("Mean Absolute Error (MAE): ", round(mae, 2))

Mean squared error (MSE):  448339175282.35
R2 Score:  -0.67
Mean Absolute Error (MAE):  532237.23